// ... existing imports ...
import { deleteComment } from './delete-comment'

// ... existing code ...

const handlers: { [k in APIPath]: APIHandler<k> } = {
  // ... existing handlers ...
  'delete-comment': deleteComment,
  // ... existing code ...
}

// ... rest of the file ...